import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-archivo antialiased bg-gray-100`}>
        <div className="flex min-h-screen">
          <SideBar />
          <main className="flex-1 flex flex-col">
            <Navbar />
            <div className="p-8 flex-1">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
